name: CI

on: [ push, workflow_dispatch, pull_request ]

jobs:
  ci:
    env:
      UV_SYSTEM_PYTHON: true
      RUFF_OUTPUT_FORMAT: github

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Ruff formater
        run: uv run ruff format --check

      - name: Ruff linter
        run: uv run ruff check

      - name: Typing checks
        run: uv run pyright

      - name: Tests
        run: PYTHONPATH=. uv run pytest tests
